#!/system/bin/sh

export PATH=$PATH:/bin

mount -o remount,rw /
mount -t rfs -o remount,rw /dev/block/stl10 /system || mount -t ext4 -o remount,rw /dev/block/stl10 /system

if ! ls /system/app/Superuser.apk
then
	cp -f /res/Superuser.apk /system/app/Superuser.apk
fi
chmod 0644 /system/app/Superuser.apk
rm -f /res/Superuser.apk

# some stupid 1-click tools put su here. kill it!
rm -f /system/bin/su
# also nuke stock recovery binary
rm -f /system/bin/recovery

if ! ls /system/xbin/su
then
	cp -f /res/su /system/xbin/su
fi
ln -s /system/xbin/su /system/bin/su
chown 0:0 /system/xbin/su
chmod 6755 /system/xbin/su
rm -f /res/su

# overclocking stuff
echo "1000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo "1000000" > /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
for blip in conf default.prop fota.rc init init.rc init.smdkc110.rc init.smdkc110.sh lib lpm.rc recovery.rc res sbin
do
	chown root.system /$blip
	chown root.system /$blip/*
done

chown root.system /lib/modules/*
chown root.system /res/images/*

exit
