#!/sbin/sh

# froyo make /sdcard a symlink to /mnt/sdcard, which confuses CWM
rm /sdcard
mkdir /sdcard

cd /sbin

setup_links()
{
	ln -s /sbin/recovery $1/busybox
	ln -s /sbin/recovery $1/[
	ln -s /sbin/recovery $1/[[
	ln -s /sbin/recovery $1/amend
	ln -s /sbin/recovery $1/ash
	ln -s /sbin/recovery $1/awk
	ln -s /sbin/recovery $1/basename
	ln -s /sbin/recovery $1/bbconfig
	ln -s /sbin/recovery $1/bunzip2
	ln -s /sbin/recovery $1/bzcat
	ln -s /sbin/recovery $1/bzip2
	ln -s /sbin/recovery $1/cal
	ln -s /sbin/recovery $1/cat
	ln -s /sbin/recovery $1/catv
	ln -s /sbin/recovery $1/chgrp
	ln -s /sbin/recovery $1/chmod
	ln -s /sbin/recovery $1/chown
	ln -s /sbin/recovery $1/chroot
	ln -s /sbin/recovery $1/cksum
	ln -s /sbin/recovery $1/clear
	ln -s /sbin/recovery $1/cmp
	ln -s /sbin/recovery $1/cp
	ln -s /sbin/recovery $1/cpio
	ln -s /sbin/recovery $1/cut
	ln -s /sbin/recovery $1/date
	ln -s /sbin/recovery $1/dc
	ln -s /sbin/recovery $1/dd
	ln -s /sbin/recovery $1/depmod
	ln -s /sbin/recovery $1/devmem
	ln -s /sbin/recovery $1/df
	ln -s /sbin/recovery $1/diff
	ln -s /sbin/recovery $1/dirname
	ln -s /sbin/recovery $1/dmesg
	ln -s /sbin/recovery $1/dos2unix
	ln -s /sbin/recovery $1/du
	ln -s /sbin/recovery $1/dump_image
	ln -s /sbin/recovery $1/echo
	ln -s /sbin/recovery $1/egrep
	ln -s /sbin/recovery $1/env
	ln -s /sbin/recovery $1/erase_image
	ln -s /sbin/recovery $1/expr
	ln -s /sbin/recovery $1/false
	ln -s /sbin/recovery $1/fdisk
	ln -s /sbin/recovery $1/fgrep
	ln -s /sbin/recovery $1/find
	ln -s /sbin/recovery $1/flash_image
	ln -s /sbin/recovery $1/fold
	ln -s /sbin/recovery $1/free
	ln -s /sbin/recovery $1/freeramdisk
	ln -s /sbin/recovery $1/fuser
	ln -s /sbin/recovery $1/getopt
	ln -s /sbin/recovery $1/grep
	ln -s /sbin/recovery $1/gunzip
	ln -s /sbin/recovery $1/gzip
	ln -s /sbin/recovery $1/head
	ln -s /sbin/recovery $1/hexdump
	ln -s /sbin/recovery $1/id
	ln -s /sbin/recovery $1/insmod
	ln -s /sbin/recovery $1/install
	ln -s /sbin/recovery $1/kill
	ln -s /sbin/recovery $1/killall
	ln -s /sbin/recovery $1/killall5
	ln -s /sbin/recovery $1/length
	ln -s /sbin/recovery $1/less
	ln -s /sbin/recovery $1/losetup
	ln -s /sbin/recovery $1/ls
	ln -s /sbin/recovery $1/lsmod
	ln -s /sbin/recovery $1/lspci
	ln -s /sbin/recovery $1/lsusb
	ln -s /sbin/recovery $1/lzop
	ln -s /sbin/recovery $1/lzopcat
	ln -s /sbin/recovery $1/md5sum
	ln -s /sbin/recovery $1/mkdir
	ln -s /sbin/recovery $1/mke2fs
	ln -s /sbin/recovery $1/mkfifo
	ln -s /sbin/recovery $1/mkfs.ext2
	ln -s /sbin/recovery $1/mknod
	ln -s /sbin/recovery $1/mkswap
	ln -s /sbin/recovery $1/mktemp
	ln -s /sbin/recovery $1/mkyaffs2image
	ln -s /sbin/recovery $1/modprobe
	ln -s /sbin/recovery $1/more
	ln -s /sbin/recovery $1/mountpoint
	ln -s /sbin/recovery $1/mv
	ln -s /sbin/recovery $1/nandroid
	ln -s /sbin/recovery $1/nice
	ln -s /sbin/recovery $1/nohup
	ln -s /sbin/recovery $1/od
	ln -s /sbin/recovery $1/patch
	ln -s /sbin/recovery $1/pgrep
	ln -s /sbin/recovery $1/pidof
	ln -s /sbin/recovery $1/pkill
	ln -s /sbin/recovery $1/printenv
	ln -s /sbin/recovery $1/printf
	ln -s /sbin/recovery $1/ps
	ln -s /sbin/recovery $1/pwd
	ln -s /sbin/recovery $1/rdev
	ln -s /sbin/recovery $1/readlink
	ln -s /sbin/recovery $1/realpath
	ln -s /sbin/recovery $1/reboot
	ln -s /sbin/recovery $1/renice
	ln -s /sbin/recovery $1/reset
	ln -s /sbin/recovery $1/rm
	ln -s /sbin/recovery $1/rmdir
	ln -s /sbin/recovery $1/rmmod
	ln -s /sbin/recovery $1/run-parts
	ln -s /sbin/recovery $1/sed
	ln -s /sbin/recovery $1/seq
	ln -s /sbin/recovery $1/setsid
	ln -s /sbin/recovery $1/sha1sum
	ln -s /sbin/recovery $1/sha256sum
	ln -s /sbin/recovery $1/sha512sum
	ln -s /sbin/recovery $1/sleep
	ln -s /sbin/recovery $1/sort
	ln -s /sbin/recovery $1/split
	ln -s /sbin/recovery $1/stat
	ln -s /sbin/recovery $1/strings
	ln -s /sbin/recovery $1/stty
	ln -s /sbin/recovery $1/swapoff
	ln -s /sbin/recovery $1/swapon
	ln -s /sbin/recovery $1/sync
	ln -s /sbin/recovery $1/sysctl
	ln -s /sbin/recovery $1/tac
	ln -s /sbin/recovery $1/tail
	ln -s /sbin/recovery $1/tar
	ln -s /sbin/recovery $1/tee
	ln -s /sbin/recovery $1/test
	ln -s /sbin/recovery $1/time
	ln -s /sbin/recovery $1/top
	ln -s /sbin/recovery $1/touch
	ln -s /sbin/recovery $1/tr
	ln -s /sbin/recovery $1/true
	ln -s /sbin/recovery $1/tty
	ln -s /sbin/recovery $1/umount
	ln -s /sbin/recovery $1/uname
	ln -s /sbin/recovery $1/uniq
	ln -s /sbin/recovery $1/unix2dos
	ln -s /sbin/recovery $1/unlzop
	ln -s /sbin/recovery $1/unyaffs
	ln -s /sbin/recovery $1/unzip
	ln -s /sbin/recovery $1/uptime
	ln -s /sbin/recovery $1/usleep
	ln -s /sbin/recovery $1/uudecode
	ln -s /sbin/recovery $1/uuencode
	ln -s /sbin/recovery $1/watch
	ln -s /sbin/recovery $1/wc
	ln -s /sbin/recovery $1/which
	ln -s /sbin/recovery $1/whoami
	ln -s /sbin/recovery $1/xargs
	ln -s /sbin/recovery $1/yes
	ln -s /sbin/recovery $1/zcat
}

setup_links /sbin
if [ ! -e /system/bin/sh ]
then
	mkdir /system/bin
	setup_links /system/bin
	ln -s /sbin/recovery /system/bin/sh
fi

mkdir -p /etc
cp /sbin/recovery.fstab /etc/recovery.fstab

umount -l /system

# run the actual recovery
recovery &
